### PR TITLE
Empty data bug fix w/changes in handler

### LINKED ISSUE #112: Creating empty data records on export
**Describe the bug**
When recording data sometimes the dashboard does not initialize the daataRecording.js file.

**To Reproduce**
We need to find a way to reproduce this

**Expected behavior**
The exported json's are not initialized

### PR DESCRIPTION
**Pull request by EUdds**
# Description

- Please include a summary of the change and which issue (if applicable) is fixed
- Resolves #112 (delete if n/a)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Checklist

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (readme)
- [ ] My changes generate no new warnings or errors
- [ ] I have added tests/examples that prove my fix is effective or that my feature works
- [ ] New and existing lint guidelines/tests/examples pass with my changes (run npm test locally)

### CODE REVIEW

File: src/public/javascripts/datainterfacing.js [hunk 1]
```diff
@@ -280,14 +280,15 @@ module.exports.findRenderable = function findRenderable() {
  */
 function createID() {
   let d = new Date();
-  return `${d.getDate()}${d.getHours()}${d.getMinutes()}${d.getSeconds()}`;
+  return `${d.getMonth() + 1}-${d.getDate()}--${d.getHours()}:${d.getMinutes()}:${d.getSeconds()}`;
```
Comment (EUdds) [inline src/public/javascripts/datainterfacing.js]: I like this a lot
